my_string = input('Введите символы ')
print("Вы ввели ", (len(my_string)), "символов")
print("Верзний регистр: ", my_string.upper())
print("Нижний регистр: ", my_string.lower())
print("Без пробелов: ", my_string.replace(" ", ""))
print("Первый символ: ", my_string[0])
print("Последний символ: ", my_string[-1])